/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirbeneran_azzah;

/**
 *
 * @author AZZAH AFIFAH
 */
public class HajiMakmur extends javax.swing.JFrame {

    /**
     * Creates new form HajiMakmur
     */
     int harga, harga1, harga2, harga3, harga4, harga5, harga6, harga7, harga8, pilihan, jumlah, uang, kembalian,total;
     String barang, barang1, barang2, barang3, barang4, barang5, barang6, barang7, barang8;
       
    public HajiMakmur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonMenu = new javax.swing.JButton();
        TextOleh = new javax.swing.JTextField();
        TextJumlah = new javax.swing.JTextField();
        TextUang = new javax.swing.JTextField();
        ButtonReset = new javax.swing.JButton();
        ButtonHasil = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kolomMenu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaHasil = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonMenu.setText("MENU");
        ButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 140, 70));
        getContentPane().add(TextOleh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 30));
        getContentPane().add(TextJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 120, 30));
        getContentPane().add(TextUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, 30));

        ButtonReset.setText("RESET");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, 30));

        ButtonHasil.setText("HASIL");
        ButtonHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHasilActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 423, -1, 30));

        ButtonExit.setText("EXIT");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 423, 70, 30));

        kolomMenu.setColumns(20);
        kolomMenu.setRows(5);
        jScrollPane1.setViewportView(kolomMenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, 90));

        TextAreaHasil.setColumns(20);
        TextAreaHasil.setRows(5);
        jScrollPane2.setViewportView(TextAreaHasil);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 330, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasakhirbeneran_azzah/Tugas Akhir.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuActionPerformed
            barang1 = "Kurma Nabi";
            harga1 = 50000;
            barang2 = "Kismis Enak";
            harga2 = 30000;
            barang3 = "Sajdah";
            harga3 = 100000;
            barang4 = "Air Zam-Zam";
            harga4 = 60000;
            barang5 = "Kain Ihram";
            harga5 = 300000;
            barang6 = "Peci";
            harga6 = 30000;
            barang7 = "Tasbih";
            harga7 = 40000;
            barang8 = "Gamis";
            harga8 = 500000;
            kolomMenu.setText  ("1." + barang1 + "(Rp" + harga1 + ")\n2." + barang2 + "(Rp" + harga2 + ")\n3." + barang3 + "(Rp" + harga3 +")\n4." + barang4 + "(Rp" + harga4 +")\n5." + barang5 + "(Rp" + harga5 +")\n6." + barang6 + "(Rp" + harga6 +")\n7." + barang7 + "(Rp" + harga7 +")\n8." + barang8 + "(Rp" + harga8 );
       
    }//GEN-LAST:event_ButtonMenuActionPerformed

    private void ButtonHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHasilActionPerformed
        pilihan = Integer.parseInt(TextOleh.getText());
       
        jumlah = Integer.parseInt(TextJumlah.getText());
      
        uang = Integer.parseInt(TextUang.getText());
        
        if (pilihan==1){
           barang1 = "Kurma Nabi";
            harga1 = 50000;
            harga = harga1;
            barang = barang1;
       
       }
         else if (pilihan==2){
             barang2 = "Kismis Enak";
            harga2 = 30000; 
            harga = harga2;
            barang = barang2;
        }
       
         else if (pilihan == 3){
              barang3 = "Sajdah";
            harga3 = 100000;
             harga = harga3;
            barang = barang3;
         }
         else if (pilihan == 4){
             barang4 = "Air Zam-Zam";
            harga4 = 60000;
            harga = harga4;
            barang = barang4;
         }
         else if (pilihan == 5){
             barang5 = "Kain Ihram";
            harga5 = 300000;
            harga = harga5;
            barang = barang5; 
         }
         else if (pilihan == 6){
             barang6 = "Peci";
            harga6 = 30000;
            harga = harga6;
            barang = barang6; 
         }     
         else if (pilihan == 7){
             barang7 = "Tasbih";
            harga7 = 40000;
            harga = harga7;
            barang = barang7; 
         }
         else if (pilihan == 8){
             barang8 = "Gamis";
            harga8 = 500000;
            harga = harga8;
            barang = barang8; 
         }
         
         kembalian = uang - jumlah * harga;
         if (kembalian>0){
             TextAreaHasil.setText("Sukron Telah belanja produk," + barang + ").\n Uang Kembalian " +kembalian);
         }
         else if (kembalian == 0){
             TextAreaHasil.setText("Sukron Telah belanja produk," + barang + ". Uang anda PAS BANGET");
             
         }
         else {
             TextAreaHasil.setText("Uangnya kurangg brayy");
         }
                 
     
    }//GEN-LAST:event_ButtonHasilActionPerformed

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        Exit brayy = new Exit();
        brayy.Keluar ();
    }//GEN-LAST:event_ButtonExitActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
       TextOleh.setText("");
       TextJumlah.setText("");
       TextUang.setText("");
       TextAreaHasil.setText("");
       kolomMenu.setText("");

    }//GEN-LAST:event_ButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HajiMakmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HajiMakmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HajiMakmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HajiMakmur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HajiMakmur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonHasil;
    private javax.swing.JButton ButtonMenu;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JTextArea TextAreaHasil;
    private javax.swing.JTextField TextJumlah;
    private javax.swing.JTextField TextOleh;
    private javax.swing.JTextField TextUang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea kolomMenu;
    // End of variables declaration//GEN-END:variables
}
